### ISSUE TITLE
Starting lamprey with RubyGems 2.5.1.

### ISSUE THREAD

**Issue by muratseyhan** [ruby-rdf/rdf-ldp#54]
Using RubyGems 2.5.1, I tried the following instructions from `README.md`.

```
$ gem install rdf-ldp
$ lamprey
```

I received the following error.

```
.../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xd14f20 rdf-ldp-0.6.0> (NoMethodError)
  from .../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
  from .../.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
  from .../.rvm/gems/ruby-2.3.0/gems/rdf-ldp-0.6.0/bin/lamprey:3:in `<top (required)>'
  from .../.rvm/gems/ruby-2.3.0/bin/lamprey:23:in `load'
  from .../.rvm/gems/ruby-2.3.0/bin/lamprey:23:in `<main>'
  from .../.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
  from .../.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Updating RubyGems seems to solve the problem.

```
$ gem update --system
...
$ gem -v 
2.6.4
$ lamprey
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
Use Ctrl-C to stop
```

**Comment by no-reply** [comment]
Thanks for the report. We're you able to capture the rubygems version that raised the error?

It seems like this is probably something in the gemspec that depends on a recent version. Depending on how far back we need to support, I'm happy to sort out compatibility.

**Comment by no-reply** [comment]
Okay, so answering issues from a phone means you'll miss relevant details. I'll see if I can repeat with 2.5.1.

**Comment by no-reply** [comment]
This looks to be related to https://github.com/rubygems/rubygems/issues/1420. 

Since this is treated as a bug upstream, I'm going to close it and defer to their solutions.
